import { Game, CategoryInfo } from "./types";

export const CATEGORIES_DATA: CategoryInfo[] = [
  {
    name: "Action",
    slug: "action",
    description: "High-octane action games, combat challenges, and thrilling battles.",
    iconName: "Flame",
    count: 0,
  },
  {
    name: "Racing",
    slug: "racing",
    description: "High-speed highway racing, stunt driving, and competitive motorsports.",
    iconName: "Car",
    count: 0,
  },
  {
    name: "Puzzle",
    slug: "puzzle",
    description: "Brain teasers, logic puzzles, matching grids, and spatial challenges.",
    iconName: "Puzzle",
    count: 0,
  },
  {
    name: "Arcade",
    slug: "arcade",
    description: "Classic retro arcade games, fast-paced reflex tests, and high-score runs.",
    iconName: "Gamepad2",
    count: 0,
  },
  {
    name: "Shooting",
    slug: "shooting",
    description: "Space shooters, target practice, and tactical blaster combat.",
    iconName: "Crosshair",
    count: 0,
  },
  {
    name: "Adventure",
    slug: "adventure",
    description: "Explore uncharted worlds, conquer dungeons, and complete epic quests.",
    iconName: "Compass",
    count: 0,
  },
  {
    name: "Sports",
    slug: "sports",
    description: "Soccer shootouts, basketball hoops, tennis rallies, and athletic glory.",
    iconName: "Trophy",
    count: 0,
  },
  {
    name: "Strategy",
    slug: "strategy",
    description: "Tower defense, tactical positioning, kingdom management, and board strategy.",
    iconName: "Shield",
    count: 0,
  },
  {
    name: "Casual",
    slug: "casual",
    description: "Relaxing, easy-to-learn games perfect for quick breaks and fun sessions.",
    iconName: "Sparkles",
    count: 0,
  },
  {
    name: "Skill",
    slug: "skill",
    description: "Test your timing, precision jumping, and lightning-fast reflexes.",
    iconName: "Zap",
    count: 0,
  },
  {
    name: "Multiplayer",
    slug: "multiplayer",
    description: "Play with and compete against friends in real-time browser matches.",
    iconName: "Users",
    count: 0,
  },
  {
    name: "Girls",
    slug: "girls",
    description: "Fashion dress-up, interior decorating, makeup artistry, and cooking fun.",
    iconName: "Heart",
    count: 0,
  },
];

export const MOCK_GAMES: Game[] = [
  {
    id: "fl-game-001",
    slug: "neon-cyber-snake",
    title: "Neon Cyber Snake",
    description: "Experience the legendary classic Snake re-imagined with sleek cyberpunk visuals, glowing neon particle trails, and responsive controls. Grow your cyber serpent by harvesting energy nodes across the glowing grid without colliding into walls or your own tail.",
    thumbnail: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/neon-snake.html",
    category: "Arcade",
    tags: ["snake", "retro", "neon", "cyberpunk", "arcade", "classic"],
    controls: "Arrow Keys or WASD to change direction. On mobile, use the on-screen D-Pad buttons.",
    instructions: "Guide your neon snake around the board to consume green energy orbs. Each orb increases your score by 10 points and elongates your snake. Avoid running into edges or colliding with your body.",
    source: "mock",
    publishedAt: "2025-01-10T12:00:00Z",
    updatedAt: "2025-02-15T09:30:00Z",
    featured: true,
    trending: true,
    rating: 4.8,
    playCount: 14250,
    status: "active",
  },
  {
    id: "fl-game-002",
    slug: "space-blaster-2099",
    title: "Space Blaster 2099",
    description: "Pilot an advanced starfighter across deep space in this adrenaline-fueled arcade space shooter. Blast incoming alien interceptors, dodge deadly plasma barrages, and protect the planetary defense grid from total annihilation.",
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/space-blaster.html",
    category: "Shooting",
    tags: ["space", "shooter", "arcade", "retro", "action", "sci-fi"],
    controls: "Left/Right Arrow keys or A/D to steer. Spacebar to fire lasers. Touch buttons supported on mobile.",
    instructions: "Destroy enemy fighters before they breach your perimeter. You have 3 ship shields per run. Every destroyed ship grants 25 combat points. Maintain your accuracy and survivability.",
    source: "mock",
    publishedAt: "2025-01-14T08:00:00Z",
    updatedAt: "2025-02-18T14:10:00Z",
    featured: true,
    trending: true,
    rating: 4.9,
    playCount: 22800,
    status: "active",
  },
  {
    id: "fl-game-003",
    slug: "cyber-runner",
    title: "Cyber Runner",
    description: "An electrifying endless runner set in a high-tech neon metropolis. Leap across rooftops, dodge laser barriers, execute double jumps, and see how far your reflexes can carry you into the digital horizon.",
    thumbnail: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/cyber-runner.html",
    category: "Action",
    tags: ["runner", "parkour", "cyberpunk", "jump", "reflex", "speed"],
    controls: "Spacebar / Up Arrow to Jump. Press twice in mid-air to Double Jump. Tap screen on mobile.",
    instructions: "Timing is everything! Jump over low spikes and double jump over towering barriers. The run gets progressively faster the longer you survive. Reach the highest distance record possible.",
    source: "mock",
    publishedAt: "2025-01-18T10:00:00Z",
    updatedAt: "2025-02-10T11:00:00Z",
    featured: true,
    trending: true,
    rating: 4.7,
    playCount: 18900,
    status: "active",
  },
  {
    id: "fl-game-004",
    slug: "cyber-2048-block-puzzle",
    title: "Cyber 2048 Block Puzzle",
    description: "The critically acclaimed math and logic puzzle game wrapped in a modern synthwave aesthetic. Slide numbered tiles across the matrix to merge identical values and work your way up to the coveted 2048 quantum block.",
    thumbnail: "https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/block-puzzle.html",
    category: "Puzzle",
    tags: ["2048", "puzzle", "numbers", "brain", "strategy", "casual"],
    controls: "Arrow keys (Up, Down, Left, Right) or WASD. Swipe on touchscreen or click directional buttons.",
    instructions: "Slide the tiles in 4 directions. When two matching numbers collide, they fuse into their sum (2+2=4, 4+4=8...). Plan ahead so you don't run out of empty slots on the 4x4 grid.",
    source: "mock",
    publishedAt: "2025-01-05T09:00:00Z",
    updatedAt: "2025-02-01T16:00:00Z",
    featured: true,
    trending: false,
    rating: 4.8,
    playCount: 31200,
    status: "active",
  },
  {
    id: "fl-game-005",
    slug: "retro-speed-racer",
    title: "Retro Speed Racer",
    description: "Get behind the wheel of a tuned supercar and weave through heavy highway traffic at blistering speeds. Test your nerve as oncoming vehicles test your lane switching precision in this thrilling 2D arcade racer.",
    thumbnail: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/speed-racer.html",
    category: "Racing",
    tags: ["racing", "cars", "speed", "highway", "arcade", "reflex"],
    controls: "Left/Right Arrow keys or A/D to steer. Touch the Steer buttons on mobile devices.",
    instructions: "Dodge civilian vehicles across four lanes. As your speed climbs past 200 KM/H, traffic patterns become tighter. Survive as long as possible without a single crash.",
    source: "mock",
    publishedAt: "2025-01-22T14:30:00Z",
    updatedAt: "2025-02-12T10:00:00Z",
    featured: true,
    trending: true,
    rating: 4.6,
    playCount: 27400,
    status: "active",
  },
  {
    id: "fl-game-006",
    slug: "quantum-brick-breaker",
    title: "Quantum Brick Breaker",
    description: "Smash through crystalline quantum barriers using bouncing photon balls and power-up paddles. A reimagined breakout experience with dynamic physics and laser bonuses.",
    thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/space-blaster.html",
    category: "Arcade",
    tags: ["breakout", "bricks", "paddle", "arcade", "retro"],
    controls: "Mouse or Left/Right Arrow keys to move the defensive paddle.",
    instructions: "Keep the photon orb in play by bouncing it off your paddle. Clear all bricks on screen to advance to the next level.",
    source: "mock",
    publishedAt: "2025-01-25T11:00:00Z",
    updatedAt: "2025-02-14T09:00:00Z",
    featured: false,
    trending: false,
    rating: 4.5,
    playCount: 9500,
    status: "active",
  },
  {
    id: "fl-game-007",
    slug: "dungeon-blade-quest",
    title: "Dungeon Blade Quest",
    description: "Embark on an epic fantasy roguelite quest through treacherous dungeons teeming with dark monsters, hidden treasure chests, and legendary magical artifacts.",
    thumbnail: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/cyber-runner.html",
    category: "Adventure",
    tags: ["rpg", "dungeon", "quest", "sword", "fantasy", "roguelite"],
    controls: "WASD to move, Spacebar to slash weapon, E to interact with chests.",
    instructions: "Navigate through procedural labyrinth floors. Defeat skeleton guards, gather gold coins, and upgrade your warrior's armor.",
    source: "mock",
    publishedAt: "2025-01-08T15:00:00Z",
    updatedAt: "2025-02-05T12:00:00Z",
    featured: false,
    trending: true,
    rating: 4.8,
    playCount: 16400,
    status: "active",
  },
  {
    id: "fl-game-008",
    slug: "hyper-drift-championship",
    title: "Hyper Drift Championship",
    description: "Tear up the asphalt in intense drift battles across neon city circuits. Master throttle control and counter-steering to maintain record-breaking slide angles.",
    thumbnail: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/speed-racer.html",
    category: "Racing",
    tags: ["drift", "racing", "cars", "turbo", "sports"],
    controls: "Arrow keys to accelerate and steer. Spacebar to engage handbrake for drifts.",
    instructions: "Enter corners at high speed and tap the handbrake to initiate a drift. Counter-steer to balance the slide and accumulate drift points.",
    source: "mock",
    publishedAt: "2025-01-29T16:00:00Z",
    updatedAt: "2025-02-16T18:00:00Z",
    featured: true,
    trending: true,
    rating: 4.7,
    playCount: 21500,
    status: "active",
  },
  {
    id: "fl-game-009",
    slug: "tactical-tower-defense",
    title: "Tactical Tower Defense",
    description: "Position tesla coils, plasma cannons, and cryogenic slowing turrets to defend your power core against waves of robotic invaders.",
    thumbnail: "https://images.unsplash.com/photo-1612287233207-6b4d7c0bbce2?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/block-puzzle.html",
    category: "Strategy",
    tags: ["tower defense", "strategy", "defense", "turrets", "tactics"],
    controls: "Mouse / Click to select and place defense towers on grid waypoints.",
    instructions: "Manage your energy reserves wisely. Build a diversified defense network combining area-of-effect splash damage with single-target armor piercers.",
    source: "mock",
    publishedAt: "2025-01-12T13:00:00Z",
    updatedAt: "2025-02-08T10:00:00Z",
    featured: false,
    trending: false,
    rating: 4.6,
    playCount: 12300,
    status: "active",
  },
  {
    id: "fl-game-010",
    slug: "penalty-shootout-pro",
    title: "Penalty Shootout Pro",
    description: "Step up to the penalty spot in the world soccer championship finals! Curve your kicks past the diving goalkeeper into the top corner netting.",
    thumbnail: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/space-blaster.html",
    category: "Sports",
    tags: ["soccer", "football", "penalty", "sports", "kick", "goal"],
    controls: "Swipe or Drag mouse to aim shot direction, elevation, and curve.",
    instructions: "Beat the goalkeeper in a best-of-five shootout. Watch the wind indicator and time your strike power meter perfectly.",
    source: "mock",
    publishedAt: "2025-01-16T17:00:00Z",
    updatedAt: "2025-02-11T13:00:00Z",
    featured: false,
    trending: true,
    rating: 4.5,
    playCount: 19800,
    status: "active",
  },
  {
    id: "fl-game-011",
    slug: "gem-match-cascade",
    title: "Gem Match Cascade",
    description: "Align dazzling magical gemstones to trigger explosive combo cascades and unlock powerful elemental runes in this relaxing match-3 adventure.",
    thumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/block-puzzle.html",
    category: "Casual",
    tags: ["match 3", "gems", "cascade", "casual", "relaxing", "puzzle"],
    controls: "Click/Tap and drag adjacent gems to swap their grid positions.",
    instructions: "Match 3 or more gems of identical color to clear them. Match 4 for lightning gems and match 5 for hyper-color rainbow jewels.",
    source: "mock",
    publishedAt: "2025-01-03T10:00:00Z",
    updatedAt: "2025-01-28T09:00:00Z",
    featured: false,
    trending: false,
    rating: 4.6,
    playCount: 15600,
    status: "active",
  },
  {
    id: "fl-game-012",
    slug: "precision-jump-master",
    title: "Precision Jump Master",
    description: "A timing and precision skill game where you must calculate leap distance between floating platforms with wind currents and moving obstacles.",
    thumbnail: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/cyber-runner.html",
    category: "Skill",
    tags: ["jump", "timing", "skill", "precision", "reflex"],
    controls: "Hold Spacebar or Tap screen to charge jump power, release to leap.",
    instructions: "Judge the distance to the next landing platform. Charge your leap carefully; overcharging or undercharging will cause you to fall into the abyss.",
    source: "mock",
    publishedAt: "2025-01-20T12:00:00Z",
    updatedAt: "2025-02-09T15:00:00Z",
    featured: false,
    trending: false,
    rating: 4.4,
    playCount: 8900,
    status: "active",
  },
  {
    id: "fl-game-013",
    slug: "battle-tanks-arena",
    title: "Battle Tanks Arena",
    description: "Engage in armored warfare across destructible obstacle courses. Ricochet cannon shells off metal walls to outsmart opponent combat vehicles.",
    thumbnail: "https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/space-blaster.html",
    category: "Action",
    tags: ["tanks", "combat", "warfare", "action", "arena"],
    controls: "WASD to drive tank, Mouse to aim turret, Left Click to fire.",
    instructions: "Use terrain cover and bounce your shells around corners to eliminate enemy tanks while evading their counter-attacks.",
    source: "mock",
    publishedAt: "2025-01-27T18:00:00Z",
    updatedAt: "2025-02-17T11:00:00Z",
    featured: false,
    trending: true,
    rating: 4.7,
    playCount: 14700,
    status: "active",
  },
  {
    id: "fl-game-014",
    slug: "fashion-stylist-runway",
    title: "Fashion Stylist Runway",
    description: "Design glamorous outfits, style high-fashion models, choose accessories, and showcase runway collections in prestigious fashion capitals.",
    thumbnail: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/block-puzzle.html",
    category: "Girls",
    tags: ["fashion", "dress up", "stylist", "makeover", "design"],
    controls: "Click/Tap wardrobe items to mix and match clothes, hairstyles, and accessories.",
    instructions: "Style your model according to the event theme (Gala, Streetwear, Red Carpet) and score top marks from the fashion jury.",
    source: "mock",
    publishedAt: "2025-01-11T09:00:00Z",
    updatedAt: "2025-01-30T14:00:00Z",
    featured: false,
    trending: false,
    rating: 4.6,
    playCount: 11200,
    status: "active",
  },
  {
    id: "fl-game-015",
    slug: "billiards-8-ball-classic",
    title: "Billiards 8-Ball Classic",
    description: "Master cue ball spin, bank shots, and potting angles in this authentic physics-based 8-ball pool simulator with single and duel modes.",
    thumbnail: "https://images.unsplash.com/photo-1534158914592-062992fbe900?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/block-puzzle.html",
    category: "Sports",
    tags: ["pool", "billiards", "8 ball", "sports", "physics"],
    controls: "Drag mouse/finger to aim cue line, pull back power meter to strike.",
    instructions: "Pocket either solids or stripes after the break, then pot the black 8-ball in the designated pocket to claim victory.",
    source: "mock",
    publishedAt: "2025-01-19T14:00:00Z",
    updatedAt: "2025-02-13T10:00:00Z",
    featured: false,
    trending: true,
    rating: 4.8,
    playCount: 24100,
    status: "active",
  },
  {
    id: "fl-game-016",
    slug: "neon-pong-reloaded",
    title: "Neon Pong Reloaded",
    description: "The retro classic that started video games, turbocharged with curved paddle strikes, speed accelerators, and multi-ball madness.",
    thumbnail: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/neon-snake.html",
    category: "Arcade",
    tags: ["pong", "retro", "classic", "arcade", "multiplayer"],
    controls: "W/S or Up/Down arrows to move paddle up and down.",
    instructions: "Deflect the glowing puck past your opponent's paddle. Striking with paddle edges creates sharp angle shots.",
    source: "mock",
    publishedAt: "2025-01-07T11:00:00Z",
    updatedAt: "2025-01-25T16:00:00Z",
    featured: false,
    trending: false,
    rating: 4.3,
    playCount: 7800,
    status: "active",
  },
  {
    id: "fl-game-017",
    slug: "sky-drift-dogfight",
    title: "Sky Drift Dogfight",
    description: "Take to the skies in high-agility jet fighters. Perform barrel rolls, lock heat-seeking missiles, and rule the aerial battlefield.",
    thumbnail: "https://images.unsplash.com/photo-1517976487507-5b3b4b45f912?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/space-blaster.html",
    category: "Shooting",
    tags: ["jets", "airplanes", "dogfight", "shooting", "action"],
    controls: "Arrow keys to maneuver pitch and yaw. Spacebar to fire 20mm cannons.",
    instructions: "Maintain target lock behind enemy bogeys and fire missiles when the target reticle turns green.",
    source: "mock",
    publishedAt: "2025-01-23T15:00:00Z",
    updatedAt: "2025-02-15T12:00:00Z",
    featured: false,
    trending: true,
    rating: 4.6,
    playCount: 17300,
    status: "active",
  },
  {
    id: "fl-game-018",
    slug: "maze-escape-chronicles",
    title: "Maze Escape Chronicles",
    description: "Navigate through shifting dark labyrinths with limited torchlight before the ancient clock runs out of sands.",
    thumbnail: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/neon-snake.html",
    category: "Puzzle",
    tags: ["maze", "labyrinth", "escape", "puzzle", "adventure"],
    controls: "Arrow keys or swipe gestures to navigate corridor turns.",
    instructions: "Find the exit portal in each labyrinth level. Collect glowing crystals along the route to illuminate secret pathways.",
    source: "mock",
    publishedAt: "2025-01-15T13:00:00Z",
    updatedAt: "2025-02-04T10:00:00Z",
    featured: false,
    trending: false,
    rating: 4.4,
    playCount: 6500,
    status: "active",
  },
  {
    id: "fl-game-019",
    slug: "ninja-slash-frenzy",
    title: "Ninja Slash Frenzy",
    description: "Slice through flying shurikens, explosive scrolls, and combat dummies in a whirlwind test of blade speed and precision.",
    thumbnail: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/cyber-runner.html",
    category: "Skill",
    tags: ["ninja", "slash", "blade", "skill", "reflex"],
    controls: "Click and drag mouse or swipe finger across the screen to slice targets.",
    instructions: "Slice targets before they drop off screen. Never slice the glowing red bomb jars or you lose a life immediately.",
    source: "mock",
    publishedAt: "2025-01-28T10:00:00Z",
    updatedAt: "2025-02-16T15:00:00Z",
    featured: true,
    trending: true,
    rating: 4.8,
    playCount: 23600,
    status: "active",
  },
  {
    id: "fl-game-020",
    slug: "crazy-kart-mayhem",
    title: "Crazy Kart Mayhem",
    description: "Fun arcade go-kart racing featuring turbo boost pads, banana peels, homing rockets, and loop-the-loop track designs.",
    thumbnail: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/speed-racer.html",
    category: "Racing",
    tags: ["kart", "racing", "powerups", "fun", "casual"],
    controls: "WASD / Arrows to drive, Spacebar to trigger collected item power-ups.",
    instructions: "Collect mystery item boxes along the racetrack and use tactical power-ups to overtake rivals on final laps.",
    source: "mock",
    publishedAt: "2025-01-21T16:00:00Z",
    updatedAt: "2025-02-14T11:00:00Z",
    featured: true,
    trending: true,
    rating: 4.7,
    playCount: 19400,
    status: "active",
  },
  {
    id: "fl-game-021",
    slug: "hex-puzzle-revolution",
    title: "Hex Puzzle Revolution",
    description: "Fit hexagonal tile blocks onto the hexagonal honeycomb board to clear complete horizontal and diagonal lines in this addictive brain game.",
    thumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/block-puzzle.html",
    category: "Puzzle",
    tags: ["hex", "puzzle", "blocks", "brain", "board"],
    controls: "Drag hexagon clusters from the bottom pool onto the honeycomb board.",
    instructions: "Create full continuous lines across any of the 3 grid axes to clear blocks and prevent grid lock.",
    source: "mock",
    publishedAt: "2025-01-13T12:00:00Z",
    updatedAt: "2025-02-06T14:00:00Z",
    featured: false,
    trending: false,
    rating: 4.5,
    playCount: 10800,
    status: "active",
  },
  {
    id: "fl-game-022",
    slug: "kingdom-defense-clash",
    title: "Kingdom Defense Clash",
    description: "Lead heroic knights, elven archers, and siege catapults to defend royal castle walls against orc warlord hordes.",
    thumbnail: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/space-blaster.html",
    category: "Strategy",
    tags: ["castle", "knights", "strategy", "defense", "war"],
    controls: "Click troop cards to summon reinforcements when mana permits.",
    instructions: "Deploy counter units against enemy formations (cavalry beats archers, spearmen beat cavalry).",
    source: "mock",
    publishedAt: "2025-01-26T14:00:00Z",
    updatedAt: "2025-02-12T17:00:00Z",
    featured: false,
    trending: true,
    rating: 4.7,
    playCount: 16100,
    status: "active",
  },
  {
    id: "fl-game-023",
    slug: "cosmic-bubble-pop",
    title: "Cosmic Bubble Pop",
    description: "Aim your stellar bubble cannon to match 3 or more matching cosmic orbs and trigger dazzling chain-reaction burst cascades.",
    thumbnail: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/block-puzzle.html",
    category: "Casual",
    tags: ["bubbles", "shooter", "casual", "match", "pop"],
    controls: "Point mouse or finger to aim trajectory, click or release to launch orb.",
    instructions: "Clear clusters before the descending bubble ceiling touches the lower boundary line.",
    source: "mock",
    publishedAt: "2025-01-09T08:00:00Z",
    updatedAt: "2025-01-27T12:00:00Z",
    featured: false,
    trending: false,
    rating: 4.4,
    playCount: 13900,
    status: "active",
  },
  {
    id: "fl-game-024",
    slug: "urban-basketball-stars",
    title: "Urban Basketball Stars",
    description: "Hit the street basketball court! Sink deep 3-pointers, time slam dunks, and rack up consecutive swish multipliers.",
    thumbnail: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/space-blaster.html",
    category: "Sports",
    tags: ["basketball", "hoops", "sports", "dunk", "streetball"],
    controls: "Click and drag back the ball to set trajectory arc, release to shoot.",
    instructions: "Score as many baskets as possible in 60 seconds. Clean swishes award bonus extra time.",
    source: "mock",
    publishedAt: "2025-01-24T17:00:00Z",
    updatedAt: "2025-02-15T16:00:00Z",
    featured: false,
    trending: true,
    rating: 4.6,
    playCount: 18200,
    status: "active",
  },
  {
    id: "fl-game-025",
    slug: "party-mini-battles",
    title: "Party Mini Battles",
    description: "A fun collection of 2-player local multiplayer minigames: thumb wars, tank duels, racing dashes, and reaction tap showdowns.",
    thumbnail: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&auto=format&fit=crop&q=80",
    embedUrl: "/embeds/neon-snake.html",
    category: "Multiplayer",
    tags: ["2 player", "multiplayer", "party", "versus", "duel"],
    controls: "Player 1 uses W key / Left screen side. Player 2 uses Up Arrow / Right screen side.",
    instructions: "Challenge a friend on the same device! First player to win 3 minigame rounds wins the crown.",
    source: "mock",
    publishedAt: "2025-01-30T15:00:00Z",
    updatedAt: "2025-02-18T12:00:00Z",
    featured: true,
    trending: true,
    rating: 4.8,
    playCount: 20100,
    status: "active",
  },
];
